version: v0.1
testName: CICDLoadTest
testPlan: test.jmx
description: 'Regression Load Test from CICD'
engineInstances: 1
failureCriteria:
    - GetAllCostumes: avg(response_time_ms) > 1000
    - percentage(error) > 20